name: Build Frida for Android

on:
  workflow_dispatch:
    inputs:
      FRIDA_VERSION:
        description: 'Frida version to build'
        required: true

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set Up NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
    
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential ninja-build python3 python3-pip clang cmake pkg-config git-core
        python3 -m pip install meson

    - name: Clone Frida and Apply Patches
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git clone https://github.com/ZuoqTr/Frida-Patchs Patchs
        git clone -b ${{ github.event.inputs.FRIDA_VERSION }} --recurse-submodules https://github.com/frida/frida frida
        cd frida/subprojects/frida-core
        git am ../../../Patchs/frida-core/*.patch

    - name: Build Frida for Android
      env:
        ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        cd frida
        ./configure --host=android-arm64
        make
        mv build/subprojects/frida-core/server/frida-server build/subprojects/frida-core/server/arm64-v8a
         
    - name: Upload Built Files
      uses: actions/upload-artifact@v4
      with:
        name: frida-android-${{ github.event.inputs.FRIDA_VERSION }}
        path: frida/build/subprojects/frida-core/server/arm64-v8a
        
